import { PrismaClient, UnitStatus } from "@prisma/client";

export async function seedKavlingTersedia(prisma: PrismaClient) {
  console.log("Seeding kavling tersedia...");

  await prisma.kavling.createMany({
    skipDuplicates: true,
    data: [
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 66,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 607999998,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "3",
        luasBangunan: 73,
        luasTanah: 66,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 607999998,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 66,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 607999998,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "8",
        luasBangunan: 73,
        luasTanah: 66,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 607999998,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "10",
        luasBangunan: 73,
        luasTanah: 66,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 607999998,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "12",
        luasBangunan: 73,
        luasTanah: 90,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 687999990,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA2",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA2",
        nomorUnit: "3",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "3",
        luasBangunan: 73,
        luasTanah: 72.7,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 630333329,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "5",
        luasBangunan: 73,
        luasTanah: 66,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 607999998,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "7",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 788000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "3",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 788000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 788000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "8",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 788000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "11",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 788000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "20",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 788000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "22",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 788000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 62,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 594666666,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "2",
        luasBangunan: 73,
        luasTanah: 66.4,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 609333331,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "3",
        luasBangunan: 73,
        luasTanah: 70.8,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 623999996,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "5",
        luasBangunan: 73,
        luasTanah: 75.2,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 638666662,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 78.3,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 648999994,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "7",
        luasBangunan: 73,
        luasTanah: 79.6,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 653333327,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "8",
        luasBangunan: 73,
        luasTanah: 80.5,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 656333327,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "9",
        luasBangunan: 73,
        luasTanah: 81.3,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 658999993,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "10",
        luasBangunan: 73,
        luasTanah: 142.5,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 862999973,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA7",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 70.8,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 623999996,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA7",
        nomorUnit: "2",
        luasBangunan: 73,
        luasTanah: 97.7,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 713666654,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "3",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "8",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "10",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "12",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "15",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "18",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "1",
        luasBangunan: 73,
        luasTanah: 71.6,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 626666663,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "2",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "3",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "5",
        luasBangunan: 73,
        luasTanah: 80,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 654666660,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 80,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 654666660,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "7",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "8",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "9",
        luasBangunan: 73,
        luasTanah: 83.1,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 664999992,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "2",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "8",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "10",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "11",
        luasBangunan: 73,
        luasTanah: 104,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 734666652,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "12",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "14",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "16",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "17",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 639000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "23",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 629000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "25",
        luasBangunan: 73,
        luasTanah: 122,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 836000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "27",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 829000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "33",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 859000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA15",
        nomorUnit: "2",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA15",
        nomorUnit: "5",
        luasBangunan: 73,
        luasTanah: 102,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 749000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA15",
        nomorUnit: "10",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 639000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA16",
        nomorUnit: "7",
        luasBangunan: 73,
        luasTanah: 143,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 936000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA16",
        nomorUnit: "9",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 2,
        hargaDasar: 879000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "6",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 829000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "8",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 829000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "10",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 829000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "12",
        luasBangunan: 73,
        luasTanah: 103,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 752000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "14",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "15",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "16",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "17",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "20",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "21",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "22",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "23",
        luasBangunan: 73,
        luasTanah: 60,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 609000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "24",
        luasBangunan: 73,
        luasTanah: 122,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 836000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "27",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 829000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "29",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 829000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "31",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 829000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "35",
        luasBangunan: 73,
        luasTanah: 120,
        namaTipe: "Aruna",
        rekeningTujuanId: 1,
        hargaDasar: 879000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA19",
        nomorUnit: "1",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 459000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA19",
        nomorUnit: "7",
        luasBangunan: 48,
        luasTanah: 123,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 639000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA19",
        nomorUnit: "8",
        luasBangunan: 48,
        luasTanah: 134,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 676000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA20",
        nomorUnit: "9",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA20",
        nomorUnit: "11",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA21",
        nomorUnit: "2",
        luasBangunan: 52,
        luasTanah: 65,
        namaTipe: "Adara",
        rekeningTujuanId: 1,
        hargaDasar: 476000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA21",
        nomorUnit: "3",
        luasBangunan: 52,
        luasTanah: 70,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 492000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA21",
        nomorUnit: "5",
        luasBangunan: 52,
        luasTanah: 75,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 509000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA21",
        nomorUnit: "6",
        luasBangunan: 48,
        luasTanah: 80,
        namaTipe: "Asvara",
        rekeningTujuanId: 2,
        hargaDasar: 496000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA21",
        nomorUnit: "7",
        luasBangunan: 52,
        luasTanah: 85,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 542000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA22",
        nomorUnit: "10",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA22",
        nomorUnit: "12",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 1,
        hargaDasar: 709000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA23",
        nomorUnit: "3",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 629000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA23",
        nomorUnit: "6",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA23",
        nomorUnit: "10",
        luasBangunan: 48,
        luasTanah: 132,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 669000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA23",
        nomorUnit: "12",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 629000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA24",
        nomorUnit: "2",
        luasBangunan: 52,
        luasTanah: 121,
        namaTipe: "Adara",
        rekeningTujuanId: 1,
        hargaDasar: 662000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA24",
        nomorUnit: "5",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 1,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA24",
        nomorUnit: "7",
        luasBangunan: 48,
        luasTanah: 81,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 498000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA25",
        nomorUnit: "3",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA25",
        nomorUnit: "6",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA25",
        nomorUnit: "8",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA25",
        nomorUnit: "9",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "1",
        luasBangunan: 52,
        luasTanah: 87,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 599000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "3",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "5",
        luasBangunan: 52,
        luasTanah: 120,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 659000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "7",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 2,
        hargaDasar: 679000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "11",
        luasBangunan: 48,
        luasTanah: 79,
        namaTipe: "Asvara",
        rekeningTujuanId: 2,
        hargaDasar: 495000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA27",
        nomorUnit: "6",
        luasBangunan: 52,
        luasTanah: 133,
        namaTipe: "Adara",
        rekeningTujuanId: 2,
        hargaDasar: 702000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA27",
        nomorUnit: "10",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 2,
        hargaDasar: 588000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA27",
        nomorUnit: "12",
        luasBangunan: 48,
        luasTanah: 120,
        namaTipe: "Asvara",
        rekeningTujuanId: 2,
        hargaDasar: 678000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "2",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 428000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "3",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 408000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "5",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 429000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "6",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 429000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "7",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 429000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "8",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 429000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "12",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 429000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "15",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 408000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "2",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "3",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "5",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "10",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "11",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "12",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "16",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 399000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "17",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "18",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "19",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "20",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "21",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "22",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "23",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "24",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "25",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 369000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "28",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 399000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "3",
        luasBangunan: 36,
        luasTanah: 62,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 376000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "5",
        luasBangunan: 36,
        luasTanah: 62,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 376000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "6",
        luasBangunan: 36,
        luasTanah: 63,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 379000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "8",
        luasBangunan: 36,
        luasTanah: 71,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 406000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "9",
        luasBangunan: 36,
        luasTanah: 154,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 712000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA31",
        nomorUnit: "1",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 399000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA31",
        nomorUnit: "6",
        luasBangunan: 36,
        luasTanah: 109,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 532000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA31",
        nomorUnit: "7",
        luasBangunan: 36,
        luasTanah: 60,
        namaTipe: "Ansara",
        rekeningTujuanId: 1,
        hargaDasar: 399000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA32",
        nomorUnit: "3",
        luasBangunan: 48,
        luasTanah: 60,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 429000000,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA32",
        nomorUnit: "6",
        luasBangunan: 48,
        luasTanah: 67,
        namaTipe: "Asvara",
        rekeningTujuanId: 1,
        hargaDasar: 431000000,
        status: UnitStatus.AVAILABLE,
      },
    ],
  });

  console.log("Seeding kavling tersedia selesai.");
}
