import { PrismaClient, UnitStatus } from "@prisma/client";

export async function seedKavling(prisma: PrismaClient) {
  await prisma.kavling.createMany({
    data: [
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 66.0,
        namaTipe: "Aruna",
        hargaDasar: 607999998.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 66.0,
        namaTipe: "Aruna",
        hargaDasar: 607999998.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 66.0,
        namaTipe: "Aruna",
        hargaDasar: 607999998.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "8",
        luasBangunan: 73.0,
        luasTanah: 66.0,
        namaTipe: "Aruna",
        hargaDasar: 607999998.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "10",
        luasBangunan: 73.0,
        luasTanah: 66.0,
        namaTipe: "Aruna",
        hargaDasar: 607999998.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA1",
        nomorUnit: "12",
        luasBangunan: 73.0,
        luasTanah: 90.0,
        namaTipe: "Aruna",
        hargaDasar: 687999990.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA2",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA2",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 72.7,
        namaTipe: "Aruna",
        hargaDasar: 630333329.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "5",
        luasBangunan: 73.0,
        luasTanah: 66.0,
        namaTipe: "Aruna",
        hargaDasar: 607999998.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA3",
        nomorUnit: "7",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 788000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 788000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 788000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "8",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 788000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "11",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 788000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "20",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 788000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA5",
        nomorUnit: "22",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 788000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 62.0,
        namaTipe: "Aruna",
        hargaDasar: 594666666.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "2",
        luasBangunan: 73.0,
        luasTanah: 66.4,
        namaTipe: "Aruna",
        hargaDasar: 609333331.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 70.8,
        namaTipe: "Aruna",
        hargaDasar: 623999996.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "5",
        luasBangunan: 73.0,
        luasTanah: 75.2,
        namaTipe: "Aruna",
        hargaDasar: 638666662.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 78.3,
        namaTipe: "Aruna",
        hargaDasar: 648999994.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "7",
        luasBangunan: 73.0,
        luasTanah: 79.6,
        namaTipe: "Aruna",
        hargaDasar: 653333327.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "8",
        luasBangunan: 73.0,
        luasTanah: 80.5,
        namaTipe: "Aruna",
        hargaDasar: 656333327.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "9",
        luasBangunan: 73.0,
        luasTanah: 81.3,
        namaTipe: "Aruna",
        hargaDasar: 658999993.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA6",
        nomorUnit: "10",
        luasBangunan: 73.0,
        luasTanah: 142.5,
        namaTipe: "Aruna",
        hargaDasar: 862999973.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA7",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 70.8,
        namaTipe: "Aruna",
        hargaDasar: 623999996.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA7",
        nomorUnit: "2",
        luasBangunan: 73.0,
        luasTanah: 97.7,
        namaTipe: "Aruna",
        hargaDasar: 713666654.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "8",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "10",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "12",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "15",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA8",
        nomorUnit: "18",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 71.6,
        namaTipe: "Aruna",
        hargaDasar: 626666663.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "2",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "5",
        luasBangunan: 73.0,
        luasTanah: 80.0,
        namaTipe: "Aruna",
        hargaDasar: 654666660.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 80.0,
        namaTipe: "Aruna",
        hargaDasar: 654666660.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "7",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "8",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 588000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA9",
        nomorUnit: "9",
        luasBangunan: 73.0,
        luasTanah: 83.1,
        namaTipe: "Aruna",
        hargaDasar: 664999992.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "2",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "3",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "5",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "7",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "8",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "9",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "12",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "14",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "16",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "23",
        luasBangunan: 48.0,
        luasTanah: 120.0,
        namaTipe: "Asvara",
        hargaDasar: 629000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "25",
        luasBangunan: 73.0,
        luasTanah: 122.0,
        namaTipe: "Aruna",
        hargaDasar: 836000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "27",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 829000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA14",
        nomorUnit: "33",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 859000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA15",
        nomorUnit: "2",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA15",
        nomorUnit: "9",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 828000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "1",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 879000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "6",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 829000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "10",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 829000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "14",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "15",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "16",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "17",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "18",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 639000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "20",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "21",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "22",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "23",
        luasBangunan: 73.0,
        luasTanah: 60.0,
        namaTipe: "Aruna",
        hargaDasar: 609000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "24",
        luasBangunan: 73.0,
        luasTanah: 122.0,
        namaTipe: "Aruna",
        hargaDasar: 836000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "27",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 829000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "29",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 829000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "31",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 829000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA17",
        nomorUnit: "35",
        luasBangunan: 73.0,
        luasTanah: 120.0,
        namaTipe: "Aruna",
        hargaDasar: 879000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA18",
        nomorUnit: "11",
        luasBangunan: 48.0,
        luasTanah: 120.0,
        namaTipe: "Asvara",
        hargaDasar: 628000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA19",
        nomorUnit: "7",
        luasBangunan: 48.0,
        luasTanah: 123.0,
        namaTipe: "Asvara",
        hargaDasar: 639000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA19",
        nomorUnit: "8",
        luasBangunan: 48.0,
        luasTanah: 134.0,
        namaTipe: "Asvara",
        hargaDasar: 676000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA21",
        nomorUnit: "3",
        luasBangunan: 52.0,
        luasTanah: 70.0,
        namaTipe: "Adara",
        hargaDasar: 492000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA21",
        nomorUnit: "8",
        luasBangunan: 48.0,
        luasTanah: 96.0,
        namaTipe: "Asvara",
        hargaDasar: 549000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA22",
        nomorUnit: "3",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 659000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA22",
        nomorUnit: "6",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 709000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA22",
        nomorUnit: "12",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 709000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA23",
        nomorUnit: "10",
        luasBangunan: 48.0,
        luasTanah: 132.0,
        namaTipe: "Asvara",
        hargaDasar: 669000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA23",
        nomorUnit: "12",
        luasBangunan: 48.0,
        luasTanah: 120.0,
        namaTipe: "Asvara",
        hargaDasar: 629000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA23",
        nomorUnit: "15",
        luasBangunan: 48.0,
        luasTanah: 120.0,
        namaTipe: "Asvara",
        hargaDasar: 629000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA24",
        nomorUnit: "1",
        luasBangunan: 52.0,
        luasTanah: 82.0,
        namaTipe: "Adara",
        hargaDasar: 582000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA24",
        nomorUnit: "2",
        luasBangunan: 52.0,
        luasTanah: 121.0,
        namaTipe: "Adara",
        hargaDasar: 662000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA24",
        nomorUnit: "5",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 659000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA24",
        nomorUnit: "9",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 659000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "3",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 659000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "5",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 659000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA26",
        nomorUnit: "7",
        luasBangunan: 48.0,
        luasTanah: 120.0,
        namaTipe: "Asvara",
        hargaDasar: 679000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA27",
        nomorUnit: "1",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 709000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA27",
        nomorUnit: "3",
        luasBangunan: 52.0,
        luasTanah: 120.0,
        namaTipe: "Adara",
        hargaDasar: 659000000.0,
        rekeningTujuanId: 2,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "6",
        luasBangunan: 48.0,
        luasTanah: 60.0,
        namaTipe: "Asvara",
        hargaDasar: 429000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "9",
        luasBangunan: 48.0,
        luasTanah: 60.0,
        namaTipe: "Asvara",
        hargaDasar: 429000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "10",
        luasBangunan: 48.0,
        luasTanah: 60.0,
        namaTipe: "Asvara",
        hargaDasar: 429000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "11",
        luasBangunan: 48.0,
        luasTanah: 60.0,
        namaTipe: "Asvara",
        hargaDasar: 429000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA28",
        nomorUnit: "12",
        luasBangunan: 48.0,
        luasTanah: 60.0,
        namaTipe: "Asvara",
        hargaDasar: 429000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "2",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "3",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "5",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "6",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "7",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "8",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "12",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "16",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 399000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "17",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "18",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "19",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "20",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "21",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "22",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "23",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "24",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "25",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA29",
        nomorUnit: "26",
        luasBangunan: 36.0,
        luasTanah: 60.0,
        namaTipe: "Ansara",
        hargaDasar: 369000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },

      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "3",
        luasBangunan: 36.0,
        luasTanah: 62.0,
        namaTipe: "Ansara",
        hargaDasar: 376000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "5",
        luasBangunan: 36.0,
        luasTanah: 62.0,
        namaTipe: "Ansara",
        hargaDasar: 376000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "6",
        luasBangunan: 36.0,
        luasTanah: 63.0,
        namaTipe: "Ansara",
        hargaDasar: 379000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA30",
        nomorUnit: "8",
        luasBangunan: 36.0,
        luasTanah: 71.0,
        namaTipe: "Ansara",
        hargaDasar: 406000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA31",
        nomorUnit: "6",
        luasBangunan: 36.0,
        luasTanah: 109.0,
        namaTipe: "Ansara",
        hargaDasar: 532000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA32",
        nomorUnit: "6",
        luasBangunan: 48.0,
        luasTanah: 67.0,
        namaTipe: "Asvara",
        hargaDasar: 431000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
      {
        perumahanId: 1,
        blok: "AA32",
        nomorUnit: "8",
        luasBangunan: 48.0,
        luasTanah: 72.0,
        namaTipe: "Asvara",
        hargaDasar: 444000000.0,
        rekeningTujuanId: 1,
        status: UnitStatus.AVAILABLE,
      },
    ],
  });
}
