import type { BaseFilterDTO } from "./BaseFilterDTO.js";
import type { SP3R, UnitStatus } from "@prisma/client";
export interface UpdateCustomerKavlingDTO {
  statusKavling?: UnitStatus | undefined;
  namaTipe?: string | undefined;
  luasBangunan?: number | undefined;
  luasTanah?: number | undefined;
  hargaDasarKavling?: number | undefined;
  rekeningTujuanId?: number | null | undefined;
  notarisId?: number | null | undefined;
  lantai?: string | undefined;
  lokasiStrategis?: string | undefined;
  tanggalAkadPpjb?: string | Date | undefined;
  akadPpjb?: string | undefined;
  tanggalAkadAjbPpat?: string | Date | undefined;
  tanggalPembayaranPph?: string | Date | undefined;
  tanggalPembayaranBphtb?: string | Date | undefined;
  pembiayaan?: string | undefined;
  sp3r?: SP3R | undefined;
  lebihTanah?: number | undefined;
  biayaStrategis?: number | undefined;
  nrBiayaKprAsuransi?: number | undefined;
  nrDiskonAngsuran?: number | undefined;
  nrDiskonCash?: number | undefined;
  nrBiayaBbn?: number | undefined;
  nrBiayaNotarisAjb?: number | undefined;
  nrBiayaAppraisal?: number | undefined;
  nrBiayaBphtb?: number | undefined;
  nrLainLain?: number | undefined;
  nrTotalSubsidi?: number | undefined;
  nrNilaiPenyerahan?: number | undefined;
  nrPpn?: number | undefined;
  nrBphtb?: number | undefined;
  nrPph?: number | undefined;
  pjBiayaKpr?: number | undefined;
  pjBiayaAsuransi?: number | undefined;
  pjDiskonAngsuran?: number | undefined;
  pjBiayaBbn?: number | undefined;
  pjBiayaAjb?: number | undefined;
  pjBiayaAppraisal?: number | undefined;
  pjBphtb?: number | undefined;
  pjLainLain?: number | undefined;
  pjTotalSubsidi?: number | undefined;
  pjNilaiPenyerahan?: number | undefined;
  pjPpn?: number | undefined;
  pjBphtbPajak?: number | undefined;
  pjPph?: number | undefined;
  pjTotalBphtbPph?: number | undefined;
  ajbNjopTanahPerMeter?: number | undefined;
  ajbNjopTanah?: number | undefined;
  ajbNjopBangunanPerMeter?: number | undefined;
  ajbNjopBangunan?: number | undefined;
  ajbNjopTotal?: number | undefined;
  ajbPpn?: number | undefined;
  ajbBphtb?: number | undefined;
  ajbPph?: number | undefined;
  ajbTotalBphtbPph?: number | undefined;
  ajbSelisihPajakPbb?: number | undefined;
  ajbUping?: number | undefined;
}
export type CustomerKavlingFilterDTO = BaseFilterDTO;
