import type { DetailKavlingPajak as PrismaDetail } from "@prisma/client";
import type { DetailKavlingPajakEntity } from "../../domain/entities/DetailKavlingPajak.js";

export class DetailKavlingPajakMapper {
  static toDomain(prismaDetail: PrismaDetail): DetailKavlingPajakEntity {
    const toNumber = (val: unknown) => (val ? Number(val) : null);

    return {
      id: prismaDetail.id,
      penjualanId: prismaDetail.penjualanId,
      notarisId: prismaDetail.notarisId,
      lantai: prismaDetail.lantai,
      luasBangunan: prismaDetail.luasBangunan,
      lokasiStrategis: prismaDetail.lokasiStrategis,
      tanggalAkadPpjb: prismaDetail.tanggalAkadPpjb,
      akadPpjb: prismaDetail.akadPpjb,
      tanggalAkadAjbPpat: prismaDetail.tanggalAkadAjbPpat,
      tanggalPembayaranPph: prismaDetail.tanggalPembayaranPph,
      tanggalPembayaranBphtb: prismaDetail.tanggalPembayaranBphtb,
      pembiayaan: prismaDetail.pembiayaan,
      sp3r: prismaDetail.sp3r,
      lebihTanah: toNumber(prismaDetail.lebihTanah),
      biayaStrategis: toNumber(prismaDetail.biayaStrategis),
      nrBiayaKprAsuransi: toNumber(prismaDetail.nrBiayaKprAsuransi),
      nrDiskonAngsuran: toNumber(prismaDetail.nrDiskonAngsuran),
      nrDiskonCash: toNumber(prismaDetail.nrDiskonCash),
      nrBiayaBbn: toNumber(prismaDetail.nrBiayaBbn),
      nrBiayaNotarisAjb: toNumber(prismaDetail.nrBiayaNotarisAjb),
      nrBiayaAppraisal: toNumber(prismaDetail.nrBiayaAppraisal),
      nrBiayaBphtb: toNumber(prismaDetail.nrBiayaBphtb),
      nrLainLain: toNumber(prismaDetail.nrLainLain),
      nrTotalSubsidi: toNumber(prismaDetail.nrTotalSubsidi),
      nrNilaiPenyerahan: toNumber(prismaDetail.nrNilaiPenyerahan),
      nrPpn: toNumber(prismaDetail.nrPpn),
      nrBphtb: toNumber(prismaDetail.nrBphtb),
      nrPph: toNumber(prismaDetail.nrPph),
      pjBiayaKpr: toNumber(prismaDetail.pjBiayaKpr),
      pjBiayaAsuransi: toNumber(prismaDetail.pjBiayaAsuransi),
      pjDiskonAngsuran: toNumber(prismaDetail.pjDiskonAngsuran),
      pjBiayaBbn: toNumber(prismaDetail.pjBiayaBbn),
      pjBiayaAjb: toNumber(prismaDetail.pjBiayaAjb),
      pjBiayaAppraisal: toNumber(prismaDetail.pjBiayaAppraisal),
      pjBphtb: toNumber(prismaDetail.pjBphtb),
      pjLainLain: toNumber(prismaDetail.pjLainLain),
      pjTotalSubsidi: toNumber(prismaDetail.pjTotalSubsidi),
      pjNilaiPenyerahan: toNumber(prismaDetail.pjNilaiPenyerahan),
      pjPpn: toNumber(prismaDetail.pjPpn),
      pjBphtbPajak: toNumber(prismaDetail.pjBphtbPajak),
      pjPph: toNumber(prismaDetail.pjPph),
      pjTotalBphtbPph: toNumber(prismaDetail.pjTotalBphtbPph),
      ajbNjopTanahPerMeter: toNumber(prismaDetail.ajbNjopTanahPerMeter),
      ajbNjopTanah: toNumber(prismaDetail.ajbNjopTanah),
      ajbNjopBangunanPerMeter: toNumber(prismaDetail.ajbNjopBangunanPerMeter),
      ajbNjopBangunan: toNumber(prismaDetail.ajbNjopBangunan),
      ajbNjopTotal: toNumber(prismaDetail.ajbNjopTotal),
      ajbPpn: toNumber(prismaDetail.ajbPpn),
      ajbBphtb: toNumber(prismaDetail.ajbBphtb),
      ajbPph: toNumber(prismaDetail.ajbPph),
      ajbTotalBphtbPph: toNumber(prismaDetail.ajbTotalBphtbPph),
      ajbSelisihPajakPbb: toNumber(prismaDetail.ajbSelisihPajakPbb),
      ajbUping: toNumber(prismaDetail.ajbUping),
    };
  }
}
